NUM_TRAINING_STEPS = int(1e+6)
NUM_TEST_GAMES = 10

ALPHA = 1e-4
GAMMA = 0.99
BATCH_SIZE = 128

ENV_INPUT_SHAPE = (3,)
ENV_NAME = 'Pendulum-v1'
NUM_ENVS = 32

LOG_STD_MIN = -2
LOG_STD_MAX = 2
ACTION_MIN = -2
ACTION_MAX = 2